language: python
sudo: required
dist: trusty
python:
  - "2.7.12"
addons:
  postgresql: "9.4"
env:
  - FLASK=0.11.1
  - FLASK=0.10.1
  - FLASK=0.9
before_install:
  - psql -c 'create database ticket_system;' -U postgres
  - export PGPASSWORD="postgres"
  - psql -f ./ticket_system/schema.sql -U postgres -d ticket_system
  - sudo add-apt-repository ppa:uwsgi/release -y
  - sudo apt-get remove -qq libzmq3
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3-source.list
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install couchdb
  - sudo apt-get install uwsgi -y
  - sudo apt-get install memcached
  - sudo apt-get install libmemcached-dev
install:
  - pip install Flask==$FLASK
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - (sleep 5; echo uwsgi --socket 127.0.0.1:3031 --wsgi-file app.py --callable app --master) &
  - memcached -u memcached -d -m 30 -l 127.0.0.1 -p 11211
  # Create a directory for the UNIX sockets
  - sudo mkdir /var/run/flask-uwsgi
  - sudo chown www-data:www-data /var/run/flask-uwsgi
  # Create a directory for the logs
  - sudo mkdir /var/log/flask-uwsgi
  - sudo chown www-data:www-data /var/log/flask-uwsgi
  # Create a directory for the configs
  - sudo mkdir /etc/flask-uwsgi
  - sudo cp flask-uwsgi.conf /etc/init/flask-uwsgi.conf
  - sudo cp flask-uwsgi.ini /etc/flask-uwsgi/flask-uwsgi.ini
  - sudo service uwsgi start
script:
  - py.test tests
after_script:
  - sudo service uwsgi stop

notifications:
  email:
    - mehty.musaev@gmail.com