language: python
services:
  - postgresql
python:
  - 2.7.12
env:
  - FLASK=0.11.1
  - FLASK=0.10.1
  - FLASK=0.9
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r requirements.txt
  - pip install -q -e .
script:
  - py.test test_ticket_system.py

notifications:
  email:
    - mehty.musaev@gmail.com