language: python
python:
  - "2.7.12"
addons:
  postgresql: "9.4"
env:
  - FLASK=0.11.1
  - FLASK=0.10.1
  - FLASK=0.9
install:
  - pip install Flask==$FLASK
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - psql -c 'create database ticket_system;' -U postgres
  - export PGPASSWORD="postgres"
  - psql -f schema.sql -U postgres -d ticket_system
  # From docs: http://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#deploying-flask
  - uwsgi --socket 127.0.0.1:3031 --wsgi-file wsgi.py --callable app --processes 4 --threads 2 --stats 127.0.0.1:9191
script:
  - py.test test_ticket_system.py

notifications:
  email:
    - mehty.musaev@gmail.com