language: python
services:
  - postgresql
python:
  - 2.7.12
env:
  - FLASK=0.11.1
  - FLASK=0.10.1
  - FLASK=0.9
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r requirements.txt
  - pip install -q -e .
before_script:
  - psql -c 'create database ticket_system;' -U postgres
  - psql -d ticket_system -a -f ticket_system.sql
  # - psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'ticket_system'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE ticket_system"
script:
  - py.test test_ticket_system.py

notifications:
  email:
    - mehty.musaev@gmail.com