language: python
services:
  - postgresql
python:
  - 2.7.12
env:
  - FLASK=0.11.1
  - FLASK=0.10.1
  - FLASK=0.9
install:
  - pip install -q Flask==$FLASK
  - pip install -q -r requirements.txt
  - pip install -q -e .
before_script:
  - git clone https://github.com/rthalley/dnspython.git
  - cd dnspython
  - python setup.py install
  - psql -c 'create database ticket_system;' -U postgres
script:
  - py.test test_ticket_system.py

notifications:
  email:
    - mehty.musaev@gmail.com